name: Deploy AI Website

on: 
 push:
   branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy Website to EC2    
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /root/github-actions-static-site
            git pull origin main

          script: |
            sudo cp /root/github-actions-static-site/index.html /var/www/html/index.html 
            sudo cp /root/github-actions-static-site/style.css /var/www/html/style.css
            sudo systemctl reload nginx
